services:
  # nodejs:
  #   container_name: code_execution_server
  #   build: 
  #     context: .
  #     target: production
  #   ports:
  #     - ${API_PORT}:${API_PORT}
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - postgres
  #     - redis
  #   restart: 'no'
  #   env_file: .env
  postgres:
    container_name: postgres_db
    image: postgres:16.0-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: unless-stopped
    env_file: .env
  redis:
    container_name: redis_db
    image: redis:7.0.4
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_db_volume:/data
    restart: unless-stopped
    env_file: .env
volumes:
  postgres_db_volume:
  redis_db_volume: